# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/Documents/FPGA-Miner/xilinx-study/pci-e/pg054/pcie_ex2-tendompcie/pcie_7x_0_ex/imports/xilinx_pcie_7x_ep_x8g2.xdc

# IP: ip/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] -quiet
